"""
Owner Preference Learning — FRANK preference engine.

Applies IRL principles to infer from the stream of approval / rejection /
editing events generated by the owner's daily interactions with the briefing:

  - category_weights    : per-domain risk tolerance (0–1, higher = owner acts more)
  - agent_weights       : per-agent trust derived from approval history
  - action_threshold    : financial impact above which owner reliably acts (≥0.5 approval rate)
  - temporal_weights    : approval rate by day-of-week (Mon=0 … Sun=6)
  - approval_rate_30d/7d: rolling rates for drift detection

Drift detection:
  Compares approval rate in last-30d vs previous-30d window.
  A >20pp drop sets drift_detected=True and lowers confidence_multiplier,
  temporarily widening confidence bounds on all recommendation scores.
"""

import json
import math
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Dict, List, Optional, Any

_FEEDBACK_PATH = Path("sage/data/owner_feedback.json")
_MODEL_PATH    = Path("sage/data/owner_preference_model.json")

CATEGORIES = ["revenue", "reputation", "cost", "staffing", "employee", "compliance", "composite"]
AGENTS     = ["PULSE", "VOICE", "SHELF", "CREW", "FRANK"]
URGENCIES  = {"critical": 1.0, "high": 0.75, "medium": 0.5, "low": 0.25}

# Drift: approval rate drop (absolute) that triggers recalibration
DRIFT_THRESHOLD = 0.20
# Minimum events needed per window before computing rates
MIN_WINDOW_EVENTS = 5


# ── Data models ───────────────────────────────────────────────────────────────

@dataclass
class FeedbackEvent:
    recommendation_id: str
    category:          str
    agent:             str
    financial_impact:  float
    urgency:           str     # critical|high|medium|low
    action:            str     # "approved" | "rejected" | "edited"
    timestamp:         str     # ISO-8601 UTC
    edit_note:         str = ""


@dataclass
class OwnerPreferenceModel:
    # Core IRL outputs
    category_weights:      Dict[str, float] = field(default_factory=lambda: {c: 0.5 for c in CATEGORIES})
    agent_weights:         Dict[str, float] = field(default_factory=lambda: {a: 0.5 for a in AGENTS})
    action_threshold:      float = 200.0
    temporal_weights:      Dict[int, float] = field(default_factory=lambda: {i: 0.5 for i in range(7)})
    # Rolling rates
    approval_rate_30d:     float = 1.0
    approval_rate_7d:      float = 1.0
    # Drift state
    drift_detected:        bool  = False
    confidence_multiplier: float = 1.0   # <1 widens score bounds post-drift
    # Metadata
    total_decisions:       int   = 0
    last_updated:          str   = ""


# ── Persistence helpers ────────────────────────────────────────────────────────

def _ensure_dir():
    _FEEDBACK_PATH.parent.mkdir(parents=True, exist_ok=True)


def load_feedback() -> List[FeedbackEvent]:
    _ensure_dir()
    if not _FEEDBACK_PATH.exists():
        return []
    try:
        raw = json.loads(_FEEDBACK_PATH.read_text())
        return [FeedbackEvent(**e) for e in raw]
    except Exception:
        return []


def _save_feedback(events: List[FeedbackEvent]):
    _ensure_dir()
    _FEEDBACK_PATH.write_text(json.dumps([asdict(e) for e in events], indent=2))


def load_model() -> OwnerPreferenceModel:
    if not _MODEL_PATH.exists():
        return OwnerPreferenceModel()
    try:
        raw = json.loads(_MODEL_PATH.read_text())
        # temporal_weights keys are stored as str in JSON
        if "temporal_weights" in raw:
            raw["temporal_weights"] = {int(k): v for k, v in raw["temporal_weights"].items()}
        return OwnerPreferenceModel(**raw)
    except Exception:
        return OwnerPreferenceModel()


def save_model(model: OwnerPreferenceModel):
    _ensure_dir()
    d = asdict(model)
    _MODEL_PATH.write_text(json.dumps(d, indent=2))


# ── Event recording ────────────────────────────────────────────────────────────

def record_feedback(
    recommendation_id: str,
    category: str,
    agent: str,
    financial_impact: float,
    urgency: str,
    action: str,
    edit_note: str = "",
) -> OwnerPreferenceModel:
    """Persist a feedback event and return the freshly-computed model."""
    events = load_feedback()
    events.append(FeedbackEvent(
        recommendation_id=recommendation_id,
        category=category,
        agent=agent,
        financial_impact=financial_impact,
        urgency=urgency,
        action=action,
        timestamp=datetime.now(timezone.utc).isoformat(),
        edit_note=edit_note,
    ))
    _save_feedback(events)
    model = compute_model(events)
    save_model(model)
    return model


# ── IRL computation ────────────────────────────────────────────────────────────

def _approval_rate(events: List[FeedbackEvent]) -> float:
    if not events:
        return 1.0
    approved = sum(1 for e in events if e.action == "approved")
    return approved / len(events)


def _window(events: List[FeedbackEvent], days_back: int, days_end: int = 0) -> List[FeedbackEvent]:
    now = datetime.now(timezone.utc)
    cutoff_start = now - timedelta(days=days_back)
    cutoff_end   = now - timedelta(days=days_end)
    result = []
    for e in events:
        try:
            ts = datetime.fromisoformat(e.timestamp)
            if ts.tzinfo is None:
                ts = ts.replace(tzinfo=timezone.utc)
            if cutoff_start <= ts <= cutoff_end:
                result.append(e)
        except Exception:
            pass
    return result


def compute_model(events: Optional[List] = None) -> OwnerPreferenceModel:
    """Derive OwnerPreferenceModel from the full event history using IRL principles."""
    if events is None:
        events = load_feedback()

    # Normalise raw dicts (e.g. loaded directly from JSON) into FeedbackEvent objects
    normalised = []
    for e in events:
        if isinstance(e, dict):
            try:
                normalised.append(FeedbackEvent(**e))
            except Exception:
                pass
        else:
            normalised.append(e)
    events = normalised

    model = OwnerPreferenceModel()
    model.total_decisions = len(events)
    model.last_updated = datetime.now(timezone.utc).isoformat()

    if not events:
        return model

    # ── Category weights (domain risk tolerance) ──────────────────────────────
    for cat in CATEGORIES:
        cat_evts = [e for e in events if e.category == cat]
        if cat_evts:
            model.category_weights[cat] = round(_approval_rate(cat_evts), 3)

    # ── Agent trust ───────────────────────────────────────────────────────────
    for ag in AGENTS:
        ag_evts = [e for e in events if e.agent == ag]
        if ag_evts:
            model.agent_weights[ag] = round(_approval_rate(ag_evts), 3)

    # ── Action threshold (financial impact level where approval rate ≥ 0.5) ──
    # Bucket impacts into $50 ranges up to $2000, find the crossover point.
    approved_impacts = sorted(e.financial_impact for e in events if e.action == "approved")
    rejected_impacts = sorted(e.financial_impact for e in events if e.action != "approved")

    if approved_impacts and rejected_impacts:
        bucket_size = 50
        max_impact  = max(max(approved_impacts), max(rejected_impacts))
        n_buckets   = max(10, int(max_impact / bucket_size) + 1)
        crossover   = model.action_threshold

        for b in range(n_buckets):
            lo = b * bucket_size
            hi = lo + bucket_size
            bucket_evts = [e for e in events if lo <= e.financial_impact < hi]
            if len(bucket_evts) >= 2:
                rate = _approval_rate(bucket_evts)
                if rate >= 0.5:
                    crossover = lo
                    break
        model.action_threshold = round(crossover, 2)

    # ── Temporal weights (day-of-week approval rates) ─────────────────────────
    for dow in range(7):
        dow_evts = []
        for e in events:
            try:
                ts = datetime.fromisoformat(e.timestamp)
                if ts.weekday() == dow:
                    dow_evts.append(e)
            except Exception:
                pass
        if dow_evts:
            model.temporal_weights[dow] = round(_approval_rate(dow_evts), 3)

    # ── Rolling rates ─────────────────────────────────────────────────────────
    last_30  = _window(events, 30)
    last_7   = _window(events, 7)
    model.approval_rate_30d = round(_approval_rate(last_30), 3) if last_30 else 1.0
    model.approval_rate_7d  = round(_approval_rate(last_7),  3) if last_7  else 1.0

    # ── Drift detection ───────────────────────────────────────────────────────
    model.drift_detected, model.confidence_multiplier = detect_drift(events)

    return model


def detect_drift(events: List[FeedbackEvent]) -> tuple:
    """
    Compare approval rate in (30d–60d ago) window vs last 30d.
    Returns (drift_detected: bool, confidence_multiplier: float).
    """
    recent   = _window(events, 30)
    previous = _window(events, 60, days_end=30)

    if len(recent) < MIN_WINDOW_EVENTS or len(previous) < MIN_WINDOW_EVENTS:
        return False, 1.0

    recent_rate   = _approval_rate(recent)
    previous_rate = _approval_rate(previous)
    drop          = previous_rate - recent_rate

    if drop >= DRIFT_THRESHOLD:
        # Confidence multiplier: shrinks proportionally, floored at 0.5
        multiplier = max(0.5, 1.0 - (drop - DRIFT_THRESHOLD) * 2)
        return True, round(multiplier, 3)
    return False, 1.0


# ── Recommendation scoring ─────────────────────────────────────────────────────

def score_recommendation(rec_dict: Dict[str, Any], model: Optional[OwnerPreferenceModel] = None) -> float:
    """
    Predict the probability that the owner will approve this recommendation.
    Returns a float in [0, 1] — higher = more likely to be acted on.

    rec_dict must have: category, agent, financial_impact, urgency
    """
    if model is None:
        model = load_model()

    cat   = rec_dict.get("category", "")
    agent = rec_dict.get("agent", "")
    impact = float(rec_dict.get("financial_impact") or rec_dict.get("impact") or 0)
    urgency = rec_dict.get("urgency", "medium")

    cat_w   = model.category_weights.get(cat, 0.5)
    agent_w = model.agent_weights.get(agent, 0.5)

    # Financial impact score: sigmoid centred on action_threshold
    threshold = model.action_threshold or 200.0
    x = (impact - threshold) / (threshold / 2 + 1)
    imp_score = 1 / (1 + math.exp(-x))

    urg_score = URGENCIES.get(urgency, 0.5)

    # Weighted composite
    raw_score = 0.30 * cat_w + 0.25 * agent_w + 0.25 * imp_score + 0.20 * urg_score

    # Post-drift: pull toward 0.5 (wider uncertainty bounds)
    if model.confidence_multiplier < 1.0:
        raw_score = 0.5 + (raw_score - 0.5) * model.confidence_multiplier

    return round(min(1.0, max(0.0, raw_score)), 4)


def reorder_recommendations(recs: list, model: Optional[OwnerPreferenceModel] = None) -> list:
    """Sort recommendations by predicted approval probability descending."""
    if model is None:
        model = load_model()
    return sorted(recs, key=lambda r: score_recommendation(
        r if isinstance(r, dict) else vars(r), model
    ), reverse=True)


# ── Personalized conflict resolution helper ────────────────────────────────────

def personalize_conflict_urgency(conflict_type: str, base_urgency: str, model: Optional[OwnerPreferenceModel] = None) -> str:
    """
    Adjust conflict urgency based on owner's demonstrated category preferences.
    If the owner rarely acts on a category, don't over-escalate merged conflicts.
    """
    if model is None:
        model = load_model()

    CONFLICT_CATEGORY_MAP = {
        "revenue_staffing_mismatch": ("revenue", "staffing"),
        "pricing_cost_overlap":      ("cost", "reputation"),
        "employee_review_overlap":   ("employee", "reputation"),
    }

    cats = CONFLICT_CATEGORY_MAP.get(conflict_type, ())
    if not cats:
        return base_urgency

    cat_scores = [model.category_weights.get(c, 0.5) for c in cats]
    avg_interest = sum(cat_scores) / len(cat_scores)

    urgency_levels = ["low", "medium", "high", "critical"]
    base_idx = urgency_levels.index(base_urgency) if base_urgency in urgency_levels else 2

    if avg_interest >= 0.7:
        # Owner consistently acts on these — keep or raise
        return base_urgency
    elif avg_interest <= 0.3:
        # Owner rarely acts on these — downgrade by one level
        return urgency_levels[max(0, base_idx - 1)]
    else:
        return base_urgency


# ── Public summary for API ─────────────────────────────────────────────────────

def get_preference_summary() -> dict:
    """Return a human-readable summary of the current preference model."""
    model = load_model()
    events = load_feedback()

    top_cats = sorted(model.category_weights.items(), key=lambda x: -x[1])
    top_agents = sorted(model.agent_weights.items(), key=lambda x: -x[1])

    insights = []
    for cat, w in top_cats[:3]:
        if w >= 0.7:
            insights.append(f"You act on {cat} alerts {int(w*100)}% of the time")
        elif w <= 0.3:
            insights.append(f"You rarely act on {cat} alerts ({int(w*100)}%)")

    return {
        "model":              vars(model) if not hasattr(model, '__dict__') else model.__dict__,
        "total_decisions":    model.total_decisions,
        "approval_rate_30d":  model.approval_rate_30d,
        "approval_rate_7d":   model.approval_rate_7d,
        "action_threshold":   model.action_threshold,
        "drift_detected":     model.drift_detected,
        "confidence_multiplier": model.confidence_multiplier,
        "category_weights":   model.category_weights,
        "agent_weights":      model.agent_weights,
        "insights":           insights,
        "recent_events":      len(_window(events, 7)),
    }
