import { useState } from 'react';
import { FileText, ChevronDown, ChevronUp, Sparkles } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export default function BriefingCard({ briefing }) {
  const [expanded, setExpanded] = useState(false);
  if (!briefing) return null;

  const lines = briefing.split('\n').filter(l => l.trim());
  const preview = lines.slice(0, 5);
  const rest = lines.slice(5);

  const renderLine = (line, idx) => {
    const trimmed = line.trim();
    const isCritical = trimmed.startsWith('!') || trimmed.includes('CRITICAL');
    const isHeader = trimmed.endsWith(':') && !trimmed.startsWith('[') && !trimmed.startsWith(' ');
    const isBullet = trimmed.startsWith('[') || trimmed.startsWith('•') || trimmed.startsWith('⚠') || trimmed.startsWith('✅') || trimmed.startsWith('🚨') || trimmed.startsWith('⏰');

    return (
      <div key={idx} className={`text-sm leading-relaxed ${
        isCritical ? 'text-red-400 font-semibold' :
        isHeader   ? 'text-slate-200 font-semibold mt-3 first:mt-0' :
        isBullet   ? 'text-slate-300 pl-2' :
                     'text-slate-500'
      }`}>
        {line}
      </div>
    );
  };

  return (
    <div className="card-solid overflow-hidden">
      <div className="px-5 py-4 border-b border-white/[0.06] flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-purple-500/20 border border-purple-500/30 flex items-center justify-center">
            <Sparkles size={14} className="text-purple-400" />
          </div>
          <div>
            <p className="font-semibold text-white text-sm">Morning Briefing</p>
            <p className="text-xs text-slate-500">Generated by FRANK orchestrator</p>
          </div>
        </div>
        {rest.length > 0 && (
          <button
            onClick={() => setExpanded(e => !e)}
            className="flex items-center gap-1.5 text-xs text-indigo-400 hover:text-indigo-300 transition-colors font-medium"
          >
            {expanded ? 'Collapse' : 'Read full briefing'}
            {expanded ? <ChevronUp size={13} /> : <ChevronDown size={13} />}
          </button>
        )}
      </div>

      <div className="px-5 py-4 space-y-0.5">
        {preview.map(renderLine)}
        <AnimatePresence>
          {expanded && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.25 }}
              className="overflow-hidden space-y-0.5 pt-0.5"
            >
              {rest.map(renderLine)}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
